# Generated by Django 4.2.7 on 2023-12-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Poetry', 'Poetry'), ('Classic', 'Classic'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Memoir', 'Memoir'), ('History', 'History'), ('Travel', 'Travel'), ('Cookbook', 'Cookbook'), ('Art', 'Art'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Science', 'Science'), ('Technology', 'Technology'), ('Self-Help', 'Self-Help'), ('Health', 'Health'), ('Education', 'Education'), ('Children', 'Children')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/media/uploads')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
