# Generated by Django 4.2.7 on 2023-12-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Poetry', 'Poetry'), ('Classic', 'Classic'), ('Biography', 'Biography'), ('Autobiography', 'Autobiography'), ('Memoir', 'Memoir'), ('History', 'History'), ('Travel', 'Travel'), ('Cookbook', 'Cookbook'), ('Art', 'Art'), ('Philosophy', 'Philosophy'), ('Religion', 'Religion'), ('Science', 'Science'), ('Technology', 'Technology'), ('Self-Help', 'Self-Help'), ('Health', 'Health'), ('Education', 'Education'), ('Children', 'Children')], max_length=50),
        ),
    ]
